### ISSUE TITLE
non standard CLA with ambiguous reference to DeveloperForce

### ISSUE THREAD

**Issue by koertkuipers** [salesforce/cla-resources#3]
hi!

your cla is nonstandard due to clause 5 (Developerforce Terms of Use). this makes it harder for people to contribute to sales force open source projects, since this will likely need review by (company) lawyer. Developerforce isnt relevant for many of your open source projects, such as for example TransmogrifAI.

also your section 5 is ambiguous. i would like to think Developerforce Terms of Use only apply if you use Developerforce, but the wording of section 5 could be interpreted to mean the terms also apply if you don't use Developerforce at all. this means the cla now includes agreements about confidentiality, broad indemnity and unlimited liability.

could you please consider have a more standard cla for projects that do not relate to Developerforce?

thank you!

**Comment by bluesomewhere** [comment]
Hi there! Thanks so much for flagging this. We definitely want to make it as easy as possible for people to contribute to our projects, so we're discussing this internally this very moment :-)

While I understand this report is about our CLA more generally, may I ask which specific project you were considering to contribute to before discovering this issue?

Thanks again for the heads up!

**Comment by koertkuipers** [comment]
hi @joshsimmons 
my particular interest is in contributing to [TransmogrifAI](https://github.com/salesforce/TransmogrifAI)

**Comment by bluesomewhere** [comment]
A quick update: we noticed there's some extraneous text in section 5 that we've since removed (probably accidentally copied in), and we're still discussing internally what needs to happen here. We're agreed that the Developerforce stuff is only needed for a subset of our open source projects, so it'll definitely come out of the CLA.

I'll let you know when we've wrapped all this up! Thank you again for opening an issue so that we're aware of the problem and can do something to fix it 😃

**Comment by bluesomewhere** [comment]
So's you know: we should have resolution on this next week. Thanks for your patience!

**Comment by bluesomewhere** [comment]
OK, resolved! We've removed the language in question. Thanks again for raising this issue 😄

**Comment by koertkuipers** [comment]
thanks! looks good
